"""Turn AGPS_Capture screenshots into the AzerothGPS_StreetView_Data addon.

Pure helpers (tested in tests/test_tools.py) plus the import and build steps sv.py runs.
"""

from __future__ import annotations

import datetime as dt
import json
import shutil
from pathlib import Path

from PIL import Image

from .savedvars import load_savedvariables

PACK = "AzerothGPS_StreetView_Data"
IMAGE_SIZE = (1024, 512)  # 2:1, powers of two (the game needs power-of-two textures)
JPEG_QUALITY = 85
SHOT_EXTS = (".jpg", ".jpeg", ".tga", ".png")
STAMP = "WoWScrnShot_%m%d%y_%H%M%S"


def pose_name(yaw: int, pitch: int) -> str:
    """Image name of a view, as the addon's Data.lua D.PoseName (yaw index 0..7, pitch degrees)."""
    if pitch in (90, -90):
        yaw = 0
    return f"y{yaw * 45:03d}_p{'-' if pitch < 0 else '+'}{abs(pitch):02d}"


ALL_POSES = [pose_name(i, p) for p in (0, 45, -45) for i in range(8)] + [pose_name(0, 90), pose_name(0, -90)]


def point_id(cont: int, x: float, y: float) -> str:
    return f"{int(cont)}-{round(x)}-{round(y)}"


def crop_2to1(img: Image.Image) -> Image.Image:
    """Centered 2:1 crop, then resized to IMAGE_SIZE."""
    w, h = img.size
    if w >= 2 * h:
        cw, ch = 2 * h, h
    else:
        cw, ch = w, w // 2
    left, top = (w - cw) // 2, (h - ch) // 2
    return img.crop((left, top, left + cw, top + ch)).resize(IMAGE_SIZE, Image.LANCZOS)


def index_screenshots(folder: Path) -> dict[str, Path]:
    """Screenshot files by stem (WoWScrnShot_MMDDYY_HHMMSS)."""
    out = {}
    if folder.is_dir():
        for p in folder.iterdir():
            if p.suffix.lower() in SHOT_EXTS and p.stem.startswith("WoWScrnShot_"):
                out[p.stem] = p
    return out


def match_shot(expected: str, shots: dict[str, Path], used: set[str]) -> Path | None:
    """The screenshot saved for a shot the addon named `expected` (to the second): that name,
    else a second or two later (the file is named when it's written), else a second earlier."""
    try:
        t = dt.datetime.strptime(expected, STAMP)
    except ValueError:
        return None
    for off in (0, 1, 2, -1):
        stem = (t + dt.timedelta(seconds=off)).strftime(STAMP)
        if stem in shots and stem not in used:
            return shots[stem]
    return None


def lua_str(s) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def index_lua(points: list[dict], version: str) -> str:
    lines = [
        "-- Generated by tools/sv.py from AGPS_Capture screenshots; do not edit.",
        "-- Pictures are screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "AzerothGPS_StreetViewPacks = AzerothGPS_StreetViewPacks or {}",
        "table.insert(AzerothGPS_StreetViewPacks, {",
        f'  name = "{PACK}", version = "{version}", ext = "jpg",',
        f'  root = "Interface\\\\AddOns\\\\{PACK}\\\\Images\\\\",',
        "  points = {",
    ]
    for p in sorted(points, key=lambda q: q["id"]):
        poses = ", ".join(f'["{n}"] = true' for n in p["poses"])
        lines.append(
            f'    {{ id = {lua_str(p["id"])}, cont = {int(p["cont"])}, x = {p["x"]:.1f}, y = {p["y"]:.1f}, '
            f'z = {p.get("z") or 0:.1f}, facing = {p["facing"]:.4f}, zone = {lua_str(p.get("zone") or "")}, '
            f'poses = {{ {poses} }} }},'
        )
    lines += ["  },", "})", ""]
    return "\n".join(lines)


def toc(version: str) -> str:
    return "\n".join([
        "## Interface: 16001",
        "## Title: AzerothGPS StreetView Data",
        "## Notes: Street view pictures for AzerothGPS StreetView. Screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "## Author: AzerothGPS",
        f"## Version: {version}",
        "",
        "Index.lua",
        "",
    ])


def read_captures(wow: Path) -> list[dict]:
    """Every AGPS_Capture spot from all accounts' SavedVariables."""
    out = []
    for sv in sorted((wow / "WTF" / "Account").glob("*/SavedVariables/AGPS_Capture.lua")):
        db = load_savedvariables(sv).get("AGPSCaptureDB") or {}
        caps = db.get("captures") or []
        if isinstance(caps, dict):
            caps = [caps[k] for k in sorted(caps)]
        out.extend(c for c in caps if isinstance(c, dict))
    return out


def import_captures(wow: Path, build: Path, log=print) -> dict:
    """Screenshots of finished captures -> build/<PACK>/Images/<id>/<pose>.jpg; the points
    are merged into build/points.json (a spot captured again replaces the older one)."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    shots = index_screenshots(wow / "Screenshots")
    used: set[str] = set()
    images = build / PACK / "Images"
    stats = {"captures": 0, "skipped": 0, "images": 0, "missing": 0}
    for cap in read_captures(wow):
        if not cap.get("done") or cap.get("x") is None:
            stats["skipped"] += 1
            continue
        pid = point_id(cap["cont"], cap["x"], cap["y"])
        old = points.get(pid)
        if old and old.get("date", "") > cap.get("date", ""):
            continue  # a newer capture of this spot is already in
        out_dir = images / pid
        poses = []
        for shot in cap.get("shots") or []:
            src = match_shot(shot.get("file", ""), shots, used)
            if not src:
                stats["missing"] += 1
                log(f"  {pid} {shot.get('pose')}: no screenshot named like {shot.get('file')}")
                continue
            used.add(src.stem)
            out_dir.mkdir(parents=True, exist_ok=True)
            with Image.open(src) as im:
                crop_2to1(im.convert("RGB")).save(out_dir / f"{shot['pose']}.jpg", "JPEG", quality=JPEG_QUALITY,
                                                  optimize=True, subsampling=2)
            poses.append(shot["pose"])
            stats["images"] += 1
        if not poses:
            continue
        points[pid] = {
            "id": pid, "cont": cap["cont"], "x": cap["x"], "y": cap["y"], "z": cap.get("z") or 0,
            "facing": cap.get("facing") or 0, "zone": cap.get("subzone") or cap.get("zone") or "",
            "mapID": cap.get("mapID"), "date": cap.get("date", ""), "build": cap.get("build", ""),
            "poses": sorted(poses),
        }
        stats["captures"] += 1
    build.mkdir(parents=True, exist_ok=True)
    points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return stats


def build_pack(build: Path, version: str | None = None) -> tuple[int, int]:
    """Write the pack's toc and Index.lua from build/points.json and drop image folders of
    points no longer listed. Returns (points, bytes of images)."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    version = version or dt.date.today().strftime("%Y.%m.%d")
    pack = build / PACK
    (pack / "Images").mkdir(parents=True, exist_ok=True)
    for d in (pack / "Images").iterdir():
        if d.is_dir() and d.name not in points:
            shutil.rmtree(d)
    (pack / f"{PACK}.toc").write_text(toc(version), encoding="utf-8")
    (pack / "Index.lua").write_text(index_lua(list(points.values()), version), encoding="utf-8")
    size = sum(f.stat().st_size for f in (pack / "Images").rglob("*.jpg"))
    return len(points), size
