"""Turn AGPS_Capture screenshots into the AzerothGPS_StreetView_Data addon.

Pure helpers (tested in tests/test_tools.py) plus the import and build steps sv.py runs.
"""

from __future__ import annotations

import datetime as dt
import json
import shutil
from pathlib import Path

from PIL import Image

from .savedvars import load_savedvariables

PACK = "AzerothGPS_StreetView_Data"
IMAGE_SIZE = (1024, 512)  # 2:1, powers of two (the game needs power-of-two textures)
JPEG_QUALITY = 85  # (single views)
CUBE_QUALITY = 75  # cube tiles: measured on real spots, q85 -> q75 saves 15% with no visible loss
# CurseForge refuses files of 2 GB or more; every pack zip stays under this (PLAN.md 4.1).
BUDGET_BYTES = 1_800_000_000
# Street view points planned at 75 yd spacing (streetview-harvester points.py on the current
# roads), for projecting a full pack from the spots built so far.
PLANNED_POINTS = {"Kalimdor": 2144, "Eastern Kingdoms": 2837, "Zephras Isle": 129}
SHOT_EXTS = (".jpg", ".jpeg", ".tga", ".png")
STAMP = "WoWScrnShot_%m%d%y_%H%M%S"


def pose_name(yaw: int, pitch: int) -> str:
    """Image name of a view, as the addon's Data.lua D.PoseName (yaw index 0..7, pitch degrees)."""
    if pitch in (90, -90):
        yaw = 0
    return f"y{yaw * 45:03d}_p{'-' if pitch < 0 else '+'}{abs(pitch):02d}"


ALL_POSES = [pose_name(i, p) for p in (0, 45, -45) for i in range(8)] + [pose_name(0, 90), pose_name(0, -90)]
# the manual capture's second straight-up and straight-down shots (turned 90 degrees; for the
# panorama only: the viewer's single views use y000)
EXTRA_POSES = ["y270_p+90", "y270_p-90"]


def point_id(cont: int, x: float, y: float) -> str:
    return f"{int(cont)}-{round(x)}-{round(y)}"


def crop_2to1(img: Image.Image) -> Image.Image:
    """Centered 2:1 crop, then resized to IMAGE_SIZE."""
    w, h = img.size
    if w >= 2 * h:
        cw, ch = 2 * h, h
    else:
        cw, ch = w, w // 2
    left, top = (w - cw) // 2, (h - ch) // 2
    return img.crop((left, top, left + cw, top + ch)).resize(IMAGE_SIZE, Image.LANCZOS)


def index_screenshots(folder: Path) -> dict[str, Path]:
    """Screenshot files by stem (WoWScrnShot_MMDDYY_HHMMSS)."""
    out = {}
    if folder.is_dir():
        for p in folder.iterdir():
            if p.suffix.lower() in SHOT_EXTS and p.stem.startswith("WoWScrnShot_"):
                out[p.stem] = p
    return out


def match_shot(expected: str, shots: dict[str, Path], used: set[str]) -> Path | None:
    """The screenshot saved for a shot the addon named `expected` (to the second): that name,
    else a second or two later (the file is named when it's written), else a second earlier."""
    try:
        t = dt.datetime.strptime(expected, STAMP)
    except ValueError:
        return None
    for off in (0, 1, 2, -1):
        stem = (t + dt.timedelta(seconds=off)).strftime(STAMP)
        if stem in shots and stem not in used:
            return shots[stem]
    return None


def lua_str(s) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def index_lua(points: list[dict], version: str) -> str:
    lines = [
        "-- Generated by tools/sv.py from AGPS_Capture screenshots; do not edit.",
        "-- Pictures are screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "AzerothGPS_StreetViewPacks = AzerothGPS_StreetViewPacks or {}",
        "table.insert(AzerothGPS_StreetViewPacks, {",
        f'  name = "{PACK}", version = "{version}", ext = "jpg",',
        f'  root = "Interface\\\\AddOns\\\\{PACK}\\\\Images\\\\",',
        "  points = {",
    ]
    for p in sorted(points, key=lambda q: q["id"]):
        poses = "" if p.get("cube") else ", ".join(f'["{n}"] = true' for n in p["poses"])
        pano = p.get("pano")
        pano_lua = f' pano = {{ cols = {pano["cols"]}, rows = {pano["rows"]} }},' if pano else ""
        cube = p.get("cube")
        if cube:
            pano_lua = f' cube = {{ pad = {cube["pad"]} }},'
        lines.append(
            f'    {{ id = {lua_str(p["id"])}, cont = {int(p["cont"])}, x = {p["x"]:.1f}, y = {p["y"]:.1f}, '
            f'z = {p.get("z") or 0:.1f}, facing = {p["facing"]:.4f}, zone = {lua_str(p.get("zone") or "")}, '
            f'poses = {{ {poses} }},{pano_lua} }},'
        )
    lines += ["  },", "})", ""]
    return "\n".join(lines)


def toc(version: str) -> str:
    return "\n".join([
        "## Interface: 16001",
        "## Title: AzerothGPS StreetView Data",
        "## Notes: Street view pictures for AzerothGPS StreetView. Screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "## Author: AzerothGPS",
        f"## Version: {version}",
        "",
        "Index.lua",
        "",
    ])


def read_captures(wow: Path) -> list[dict]:
    """Every AGPS_Capture spot from all accounts' SavedVariables."""
    out = []
    for sv in sorted((wow / "WTF" / "Account").glob("*/SavedVariables/AGPS_Capture.lua")):
        db = load_savedvariables(sv).get("AGPSCaptureDB") or {}
        caps = db.get("captures") or []
        if isinstance(caps, dict):
            caps = [caps[k] for k in sorted(caps)]
        out.extend(c for c in caps if isinstance(c, dict))
    return out


def import_captures(wow: Path, build: Path, log=print) -> dict:
    """Screenshots of finished captures -> build/<PACK>/Images/<id>/<pose>.jpg; the points
    are merged into build/points.json (a spot captured again replaces the older one)."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    shots = index_screenshots(wow / "Screenshots")
    used: set[str] = set()
    images = build / PACK / "Images"
    stats = {"captures": 0, "skipped": 0, "images": 0, "missing": 0}
    for cap in read_captures(wow):
        if not cap.get("done") or cap.get("x") is None:
            stats["skipped"] += 1
            continue
        pid = point_id(cap["cont"], cap["x"], cap["y"])
        old = points.get(pid)
        if old and old.get("date", "") > cap.get("date", ""):
            continue  # a newer capture of this spot is already in
        out_dir = images / pid
        poses, raw = [], []
        keep_cube = bool(old and old.get("date") == cap.get("date", "") and old.get("cube"))
        for shot in cap.get("shots") or []:
            src = match_shot(shot.get("file", ""), shots, used)
            if not src:
                stats["missing"] += 1
                log(f"  {pid} {shot.get('pose')}: no screenshot named like {shot.get('file')}")
                continue
            used.add(src.stem)
            if not keep_cube:  # (a stitched spot shows its cube: the single views would only add size)
                out_dir.mkdir(parents=True, exist_ok=True)
                with Image.open(src) as im:
                    crop_2to1(im.convert("RGB")).save(out_dir / f"{shot['pose']}.jpg", "JPEG", quality=JPEG_QUALITY,
                                                      optimize=True, subsampling=2)
            poses.append(shot["pose"])
            raw.append({"pose": shot["pose"], "file": src.name, "facing": shot.get("facing")})
            stats["images"] += 1
        if not poses:
            continue
        points[pid] = {
            "id": pid, "cont": cap["cont"], "x": cap["x"], "y": cap["y"], "z": cap.get("z") or 0,
            "facing": cap.get("facing") or 0, "zone": cap.get("subzone") or cap.get("zone") or "",
            "mapID": cap.get("mapID"), "date": cap.get("date", ""), "build": cap.get("build", ""),
            "poses": sorted(poses), "shots": raw,
        }
        if keep_cube:
            points[pid]["cube"] = old["cube"]  # (the same capture again: its cube still fits)
        stats["captures"] += 1
    build.mkdir(parents=True, exist_ok=True)
    points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return stats


CUBE_SIZE = 1024  # pixels per side-face tile (a quarter face plus its pad): about 20 per degree
POLE_SIZE = 512  # ... per straight-up / straight-down tile: sky and ground need less detail


def write_cube(shots, out_dir: Path, size: int = CUBE_SIZE, pole: int = POLE_SIZE,
               quality: int = CUBE_QUALITY, log=print) -> dict:
    """Calibrate and stitch one spot's pictures (stitch.Shot list) into its cube tiles in
    out_dir (<face><col><row>.jpg). Returns the spot's cube description for the pack (and a
    flat preview under the key "preview": an RGB array). Shared with streetview-harvester."""
    import numpy as np

    from . import stitch

    rig = stitch.calibrate(shots, log=log)
    flat = stitch.panorama(shots, rig, 2048)  # (fills any gap; also a picture to look at)
    grays = [stitch._gray(sh.img, 320) for sh in shots]
    mismatch = stitch.mismatch(shots, grays, rig, stitch.pairs(shots))
    out_dir.mkdir(parents=True, exist_ok=True)
    for f in out_dir.glob("*.jpg"):
        f.unlink()
    for face in stitch.FACES:
        n = pole if face in ("U", "D") else size
        for name, arr in stitch.cube_tiles(shots, rig, n, stitch.CUBE_PAD, fill=flat, faces=[face]).items():
            Image.fromarray(arr).save(out_dir / f"{name}.jpg", "JPEG", quality=quality, optimize=True, subsampling=2)
    return {"size": size, "pole": pole, "quality": quality, "pad": stitch.CUBE_PAD, "hfov": round(rig.hfov, 2),
            "pitch": {k: round(v, 2) for k, v in rig.pitch.items()},
            "yaw_off": {k: round(v, 2) for k, v in rig.yaw_off.items()},
            "mismatch": round(float(mismatch), 2), "preview": np.asarray(flat)}


def stitch_points(wow: Path, build: Path, size: int = CUBE_SIZE, only: set[str] | None = None,
                  force: bool = False, log=print) -> int:
    """Stitch each captured spot's screenshots into a cube the viewer can look around in (see
    write_cube): build/<PACK>/Images/<id>/cube/, plus a flat 360-degree copy in
    build/debug/<id>.jpg to look at. The spot's single views leave the pack (the cube replaces
    them). Spots that already have one are skipped unless `force`."""
    import math
    import shutil as sh

    import numpy as np

    from . import stitch

    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    shots_dir = wow / "Screenshots"
    done = 0
    for pid, p in sorted(points.items()):
        if (only and pid not in only) or (p.get("cube") and not force) or not p.get("shots"):
            continue
        facing0 = p["facing"]
        shots = []
        for s in p["shots"]:
            src = shots_dir / s["file"]
            pitch = int(s["pose"].split("_p")[1])
            if not src.exists() or s.get("facing") is None or pitch not in stitch.RINGS:
                continue
            yaw = math.remainder(s["facing"] - facing0, 2 * math.pi)
            with Image.open(src) as im:
                shots.append(stitch.Shot(np.asarray(im.convert("RGB")), yaw, stitch.RINGS[pitch]))
        if len(shots) < 8:
            log(f"  {pid}: only {len(shots)} screenshots found, not stitched")
            continue
        log(f"stitching {pid} ({len(shots)} pictures)")
        base = build / PACK / "Images" / pid
        cube = write_cube(shots, base / "cube", size, log=log)
        preview = cube.pop("preview")
        if (base / "pano").exists():
            sh.rmtree(base / "pano")  # (the older flat tiles)
        for f in base.glob("*.jpg"):
            f.unlink()  # (the single views: the cube replaces them)
        (build / "debug").mkdir(parents=True, exist_ok=True)
        Image.fromarray(preview).save(build / "debug" / f"{pid}.jpg", "JPEG", quality=90)
        p.pop("pano", None)
        p["cube"] = cube
        done += 1
        points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return done


def budget(build: Path) -> str:
    """How big a full pack would be at the size per spot built so far, against CurseForge's
    limit: a few lines for the tools to print."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    sizes = []
    for pid, p in points.items():
        d = build / PACK / "Images" / pid
        if p.get("cube") and d.exists():
            sizes.append(sum(f.stat().st_size for f in d.rglob("*.jpg")))
    if not sizes:
        return "size: no stitched spots yet"
    avg = sum(sizes) / len(sizes)
    total = sum(PLANNED_POINTS.values())
    lines = [f"size: {avg / 1e3:.0f} KB per spot (average of {len(sizes)}); all {total} planned spots "
             f"would be {avg * total / 1e9:.2f} GB (limit per CurseForge file {BUDGET_BYTES / 1e9:.1f} GB)"]
    for name, n in PLANNED_POINTS.items():
        gb = avg * n / 1e9
        lines.append(f"  {name}: {n} spots, {gb:.2f} GB" + ("  OVER THE LIMIT" if gb * 1e9 > BUDGET_BYTES else ""))
    return "\n".join(lines)


def import_harvest(folder: Path, build: Path, log=print) -> dict:
    """Points exported by streetview-harvester (<folder>/<id>/meta.json + views/*.jpg) into
    build/points.json and the pack's images. Only the views are used for now (the viewer shows
    one view at a time); the panoramas stay in the export folder."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    stats = {"points": 0, "images": 0, "skipped": 0}
    for meta_file in sorted(folder.glob("*/meta.json")):
        meta = json.loads(meta_file.read_text(encoding="utf-8"))
        pid = meta.get("id")
        views = meta_file.parent / "views"
        if not pid or pid != point_id(meta["cont"], meta["x"], meta["y"]) or not views.is_dir():
            stats["skipped"] += 1
            log(f"  skipped {meta_file.parent.name}: no id, a mismatched id or no views")
            continue
        out_dir = build / PACK / "Images" / pid
        out_dir.mkdir(parents=True, exist_ok=True)
        poses = []
        for img in sorted(views.glob("*.jpg")):
            if img.stem in ALL_POSES:
                shutil.copy2(img, out_dir / img.name)
                poses.append(img.stem)
                stats["images"] += 1
        points[pid] = {
            "id": pid, "cont": meta["cont"], "x": meta["x"], "y": meta["y"], "z": meta.get("z") or 0,
            "facing": meta.get("facing") or 0, "zone": meta.get("zone") or "", "mapID": meta.get("mapID"),
            "date": meta.get("captured", ""), "build": meta.get("client_build", ""), "poses": sorted(poses),
            "source": "harvester",
        }
        stats["points"] += 1
    build.mkdir(parents=True, exist_ok=True)
    points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return stats


def build_pack(build: Path, version: str | None = None) -> tuple[int, int]:
    """Write the pack's toc and Index.lua from build/points.json and drop image folders of
    points no longer listed. Returns (points, bytes of images)."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    version = version or dt.date.today().strftime("%Y.%m.%d")
    pack = build / PACK
    (pack / "Images").mkdir(parents=True, exist_ok=True)
    for d in (pack / "Images").iterdir():
        if d.is_dir() and d.name not in points:
            shutil.rmtree(d)
    (pack / f"{PACK}.toc").write_text(toc(version), encoding="utf-8")
    (pack / "Index.lua").write_text(index_lua(list(points.values()), version), encoding="utf-8")
    size = sum(f.stat().st_size for f in (pack / "Images").rglob("*.jpg"))
    if size > BUDGET_BYTES:
        raise SystemExit(f"The pack is {size / 1e9:.2f} GB: over the {BUDGET_BYTES / 1e9:.1f} GB budget "
                         "for one CurseForge file. Split it or lower the tile size first.")
    return len(points), size
