"""Street view data: captured spots -> master tiles -> the standard (SD) pack addons.

  build/points.json            every spot: where, its facing, its shots, its cube's numbers
  build/master/<id>/cube/      the spot's cube tiles at full (HD) resolution: the source for packs
  build/master/<id>/views/     single views of a spot not stitched yet
  build/packs/<name>/          the pack addons (packs.json: one per continent), SD tiles scaled
                               down from the master, each under the CurseForge budget

Pure helpers (tested in tests/test_tools.py) plus the import and build steps sv.py runs.
"""

from __future__ import annotations

import datetime as dt
import json
import time
import re
import shutil
from pathlib import Path

from PIL import Image

from .savedvars import load_savedvariables

ROOT = Path(__file__).resolve().parents[2]
LEGACY_PACK = "AzerothGPS_StreetView_Data"  # (the single pack of the first builds)
# addons of earlier layouts, removed from the game by `sv.cmd install` (the pictures are in the viewer now)
LEGACY_PACKS = [LEGACY_PACK, "AzerothGPS_StreetView_Kalimdor", "AzerothGPS_StreetView_EasternKingdoms"]
IMAGE_SIZE = (1024, 512)  # 2:1, powers of two (the game needs power-of-two textures)
JPEG_QUALITY = 85  # (single views)


def load_config(path: Path | None = None) -> dict:
    """packs.json: the packs, their tile sizes and the budget."""
    return json.loads((path or ROOT / "packs.json").read_text(encoding="utf-8"))


CONFIG = load_config()
BUDGET_BYTES = CONFIG["budget_bytes"]
CUBE_QUALITY = CONFIG["master"]["quality"]


def is_manual(point: dict) -> bool:
    """A spot from the user's own screenshots (AGPS_Capture on their real account): kept in the
    master for checking renders against, never shipped in a pack."""
    return point.get("source") == "manual" or (point.get("source") != "harvester" and "shots" in point)


def pack_for(cfg: dict, point: dict) -> dict | None:
    """The SD pack a point belongs in (by continent), or None."""
    for pk in cfg["sd"]["packs"]:
        if int(point["cont"]) in pk["continents"]:
            return pk
    return None


SHOT_EXTS = (".jpg", ".jpeg", ".tga", ".png")
STAMP = "WoWScrnShot_%m%d%y_%H%M%S"


def pose_name(yaw: int, pitch: int) -> str:
    """Image name of a view, as the addon's Data.lua D.PoseName (yaw index 0..7, pitch degrees)."""
    if pitch in (90, -90):
        yaw = 0
    return f"y{yaw * 45:03d}_p{'-' if pitch < 0 else '+'}{abs(pitch):02d}"


ALL_POSES = [pose_name(i, p) for p in (0, 45, -45) for i in range(8)] + [pose_name(0, 90), pose_name(0, -90)]
# the manual capture's second straight-up and straight-down shots (turned 90 degrees; for the
# panorama only: the viewer's single views use y000)
EXTRA_POSES = ["y270_p+90", "y270_p-90"]


def point_id(cont: int, x: float, y: float) -> str:
    return f"{int(cont)}-{round(x)}-{round(y)}"


def id_matches(pid: str, cont: int, x: float, y: float) -> bool:
    """Whether a spot's id names its place. The id comes from the exact position and the
    meta's x/y may be rounded to 0.1 yd, so a coordinate on a .5 can round either way:
    allow up to 0.55 yd each way."""
    m = re.fullmatch(r"(-?\d+)-(-?\d+)-(-?\d+)", pid or "")
    return bool(m) and int(m[1]) == int(cont) and abs(int(m[2]) - x) <= 0.55 and abs(int(m[3]) - y) <= 0.55


def crop_2to1(img: Image.Image) -> Image.Image:
    """Centered 2:1 crop, then resized to IMAGE_SIZE."""
    w, h = img.size
    if w >= 2 * h:
        cw, ch = 2 * h, h
    else:
        cw, ch = w, w // 2
    left, top = (w - cw) // 2, (h - ch) // 2
    return img.crop((left, top, left + cw, top + ch)).resize(IMAGE_SIZE, Image.LANCZOS)


def index_screenshots(folder: Path) -> dict[str, Path]:
    """Screenshot files by stem (WoWScrnShot_MMDDYY_HHMMSS)."""
    out = {}
    if folder.is_dir():
        for p in folder.iterdir():
            if p.suffix.lower() in SHOT_EXTS and p.stem.startswith("WoWScrnShot_"):
                out[p.stem] = p
    return out


def match_shot(expected: str, shots: dict[str, Path], used: set[str]) -> Path | None:
    """The screenshot saved for a shot the addon named `expected` (to the second): that name,
    else a second or two later (the file is named when it's written), else a second earlier."""
    try:
        t = dt.datetime.strptime(expected, STAMP)
    except ValueError:
        return None
    for off in (0, 1, 2, -1):
        stem = (t + dt.timedelta(seconds=off)).strftime(STAMP)
        if stem in shots and stem not in used:
            return shots[stem]
    return None


def lua_str(s) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def index_lua(points: list[dict], version: str, name: str = LEGACY_PACK) -> str:
    lines = [
        "-- Generated by tools/sv.py; do not edit.",
        "-- Pictures are screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "AzerothGPS_StreetViewPacks = AzerothGPS_StreetViewPacks or {}",
        "table.insert(AzerothGPS_StreetViewPacks, {",
        f'  name = "{name}", version = "{version}", ext = "jpg",',
        f'  root = "Interface\\\\AddOns\\\\{name}\\\\Images\\\\",',
        "  points = {",
    ]
    for p in sorted(points, key=lambda q: q["id"]):
        poses = "" if p.get("cube") else ", ".join(f'["{n}"] = true' for n in p["poses"])
        cube = p.get("cube")
        cube_lua = f' cube = {{ pad = {cube["pad"]} }},' if cube else ""
        lines.append(
            f'    {{ id = {lua_str(p["id"])}, cont = {int(p["cont"])}, x = {p["x"]:.1f}, y = {p["y"]:.1f}, '
            f'z = {p.get("z") or 0:.1f}, facing = {p["facing"]:.4f}, zone = {lua_str(p.get("zone") or "")}, '
            f'poses = {{ {poses} }},{cube_lua} }},'
        )
    lines += ["  },", "})", ""]
    return "\n".join(lines)


def toc(version: str, title: str = "AzerothGPS StreetView Data") -> str:
    return "\n".join([
        "## Interface: 16001",
        f"## Title: {title}",
        "## Notes: Street view pictures for AzerothGPS StreetView. Screenshots of World of Warcraft (c) Blizzard Entertainment.",
        "## Author: AzerothGPS",
        f"## Version: {version}",
        # (a dependency of the viewer: the game lists the pack under it; the viewer reads the
        # packs at login, after every add-on has loaded, so it doesn't list them itself)
        "## Dependencies: AzerothGPS_StreetView",
        "## IconTexture: Interface\\AddOns\\AzerothGPS_StreetView\\Media\\Figure",
        "",
        "Index.lua",
        "",
    ])


def read_captures(wow: Path) -> list[dict]:
    """Every AGPS_Capture spot from all accounts' SavedVariables."""
    out = []
    for sv in sorted((wow / "WTF" / "Account").glob("*/SavedVariables/AGPS_Capture.lua")):
        db = load_savedvariables(sv).get("AGPSCaptureDB") or {}
        caps = db.get("captures") or []
        if isinstance(caps, dict):
            caps = [caps[k] for k in sorted(caps)]
        out.extend(c for c in caps if isinstance(c, dict))
    return out


def import_captures(wow: Path, build: Path, log=print) -> dict:
    """Screenshots of finished captures -> build/master/<id>/views/<pose>.jpg (until the spot
    is stitched); the points are merged into build/points.json (a spot captured again
    replaces the older one)."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    shots = index_screenshots(wow / "Screenshots")
    used: set[str] = set()
    images = build / "master"
    stats = {"captures": 0, "skipped": 0, "images": 0, "missing": 0}
    for cap in read_captures(wow):
        if not cap.get("done") or cap.get("x") is None:
            stats["skipped"] += 1
            continue
        pid = point_id(cap["cont"], cap["x"], cap["y"])
        old = points.get(pid)
        if old and old.get("date", "") > cap.get("date", ""):
            continue  # a newer capture of this spot is already in
        out_dir = images / pid / "views"
        poses, raw = [], []
        keep_cube = bool(old and old.get("date") == cap.get("date", "") and old.get("cube"))
        for shot in cap.get("shots") or []:
            src = match_shot(shot.get("file", ""), shots, used)
            if not src:
                stats["missing"] += 1
                log(f"  {pid} {shot.get('pose')}: no screenshot named like {shot.get('file')}")
                continue
            used.add(src.stem)
            if not keep_cube:  # (a stitched spot shows its cube: the single views would only add size)
                out_dir.mkdir(parents=True, exist_ok=True)
                with Image.open(src) as im:
                    crop_2to1(im.convert("RGB")).save(out_dir / f"{shot['pose']}.jpg", "JPEG", quality=JPEG_QUALITY,
                                                      optimize=True, subsampling=2)
            poses.append(shot["pose"])
            raw.append({"pose": shot["pose"], "file": src.name, "facing": shot.get("facing")})
            stats["images"] += 1
        if not poses:
            continue
        points[pid] = {
            "id": pid, "cont": cap["cont"], "x": cap["x"], "y": cap["y"], "z": cap.get("z") or 0,
            "facing": cap.get("facing") or 0, "zone": cap.get("subzone") or cap.get("zone") or "",
            "mapID": cap.get("mapID"), "date": cap.get("date", ""), "build": cap.get("build", ""),
            "poses": sorted(poses), "shots": raw, "source": "manual",
        }
        if keep_cube:
            points[pid]["cube"] = old["cube"]  # (the same capture again: its cube still fits)
        stats["captures"] += 1
    build.mkdir(parents=True, exist_ok=True)
    points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return stats


CUBE_SIZE = CONFIG["master"]["tile"]  # master side-face tiles: about 20 pixels a degree
POLE_SIZE = CONFIG["master"]["pole"]  # ... straight-up / straight-down: sky and ground need less


def write_cube(shots, out_dir: Path, size: int = CUBE_SIZE, pole: int = POLE_SIZE,
               quality: int = CUBE_QUALITY, log=print) -> dict:
    """Calibrate and stitch one spot's pictures (stitch.Shot list) into its cube tiles in
    out_dir (<face><col><row>.jpg). Returns the spot's cube description for the pack (and a
    flat preview under the key "preview": an RGB array). Shared with streetview-harvester."""
    import numpy as np

    from . import stitch

    rig = stitch.calibrate(shots, log=log)
    shots, repaired = stitch.repair(shots, rig, log=log)  # (pictures taken at the wrong angle)
    if repaired:
        rig = stitch.calibrate(shots, rig, log=log)
    flat = stitch.panorama(shots, rig, 2048)  # (fills any gap; also a picture to look at)
    grays = [stitch._gray(sh.img, 320) for sh in shots]
    mismatch = stitch.mismatch(shots, grays, rig, stitch.pairs(shots))
    out_dir.mkdir(parents=True, exist_ok=True)
    for f in out_dir.glob("*.jpg"):
        f.unlink()
    for face in stitch.FACES:
        n = pole if face in ("U", "D") else size
        for name, arr in stitch.cube_tiles(shots, rig, n, stitch.CUBE_PAD, fill=flat, faces=[face]).items():
            Image.fromarray(arr).save(out_dir / f"{name}.jpg", "JPEG", quality=quality, optimize=True, subsampling=2)
    return {"size": size, "pole": pole, "quality": quality, "pad": stitch.CUBE_PAD, "hfov": round(rig.hfov, 2),
            "pitch": {k: round(v, 2) for k, v in rig.pitch.items()},
            "yaw_off": {k: round(v, 2) for k, v in rig.yaw_off.items()},
            "mismatch": round(float(mismatch), 2), "repaired": repaired, "preview": np.asarray(flat)}


def stitch_points(wow: Path, build: Path, size: int = CUBE_SIZE, only: set[str] | None = None,
                  force: bool = False, log=print) -> int:
    """Stitch each captured spot's screenshots into a cube the viewer can look around in (see
    write_cube): build/master/<id>/cube/, plus a flat 360-degree copy in build/debug/<id>.jpg
    to look at. The spot's single views go (the cube replaces them). Spots that already have
    one are skipped unless `force`."""
    import math
    import shutil as sh

    import numpy as np

    from . import stitch

    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    shots_dir = wow / "Screenshots"
    done = 0
    for pid, p in sorted(points.items()):
        if (only and pid not in only) or (p.get("cube") and not force) or not p.get("shots"):
            continue
        facing0 = p["facing"]
        shots = []
        for s in p["shots"]:
            src = shots_dir / s["file"]
            pitch = int(s["pose"].split("_p")[1])
            if not src.exists() or s.get("facing") is None or pitch not in stitch.RINGS:
                continue
            yaw = math.remainder(s["facing"] - facing0, 2 * math.pi)
            with Image.open(src) as im:
                shots.append(stitch.Shot(np.asarray(im.convert("RGB")), yaw, stitch.RINGS[pitch]))
        if len(shots) < 8:
            log(f"  {pid}: only {len(shots)} screenshots found, not stitched")
            continue
        log(f"stitching {pid} ({len(shots)} pictures)")
        base = build / "master" / pid
        cube = write_cube(shots, base / "cube", size, log=log)
        preview = cube.pop("preview")
        if (base / "pano").exists():
            sh.rmtree(base / "pano")  # (the older flat tiles)
        if (base / "views").exists():
            sh.rmtree(base / "views")  # (the single views: the cube replaces them)
        (build / "debug").mkdir(parents=True, exist_ok=True)
        Image.fromarray(preview).save(build / "debug" / f"{pid}.jpg", "JPEG", quality=90)
        p.pop("pano", None)
        p["cube"] = cube
        done += 1
        points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return done


def import_harvest(folder: Path, build: Path, log=print) -> dict:
    """Points exported by streetview-harvester (<folder>/<id>/meta.json + cube/*.jpg, stitched
    there with this repo's write_cube) into build/points.json and the master."""
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    stats = {"points": 0, "images": 0, "skipped": 0}
    for meta_file in sorted(folder.glob("*/meta.json")):
        meta = json.loads(meta_file.read_text(encoding="utf-8"))
        pid = meta.get("id")
        cube = meta_file.parent / "cube"
        tiles = sorted(cube.glob("*.jpg")) if cube.is_dir() else []
        if not id_matches(pid, meta["cont"], meta["x"], meta["y"]) or len(tiles) != 24 or not meta.get("cube"):
            stats["skipped"] += 1
            log(f"  skipped {meta_file.parent.name}: no id, a mismatched id, or not a whole cube")
            continue
        base = build / "master" / pid
        if base.exists():
            shutil.rmtree(base)
        (base / "cube").mkdir(parents=True)
        for t in tiles:
            shutil.copy2(t, base / "cube" / t.name)
            stats["images"] += 1
        points[pid] = {
            "id": pid, "cont": meta["cont"], "x": meta["x"], "y": meta["y"], "z": meta.get("z") or 0,
            "facing": meta.get("facing") or 0, "zone": meta.get("zone") or "", "mapID": meta.get("mapID"),
            "date": meta.get("captured", ""), "build": meta.get("client_build", ""), "poses": [],
            "cube": meta["cube"], "source": "harvester", "imported_at": int(time.time()),
        }
        stats["points"] += 1
    build.mkdir(parents=True, exist_ok=True)
    points_file.write_text(json.dumps(points, indent=1), encoding="utf-8")
    return stats


def migrate(build: Path) -> None:
    """The first builds kept everything in one pack folder: move its spots into the master."""
    old = build / LEGACY_PACK / "Images"
    if not old.is_dir():
        return
    for d in old.iterdir():
        if not d.is_dir():
            continue
        dst = build / "master" / d.name
        if (d / "cube").is_dir() and not (dst / "cube").exists():
            dst.mkdir(parents=True, exist_ok=True)
            shutil.move(str(d / "cube"), str(dst / "cube"))
        views = [f for f in d.glob("*.jpg")]
        if views and not (dst / "views").exists() and not (dst / "cube").exists():
            (dst / "views").mkdir(parents=True, exist_ok=True)
            for f in views:
                shutil.move(str(f), str(dst / "views" / f.name))
    shutil.rmtree(build / LEGACY_PACK)


def _scaled(src: Path, dst: Path, px: int, quality: int) -> None:
    """dst: master tile src scaled to px (kept when already newer than the master)."""
    if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as im:
        im = im.convert("RGB")
        if im.width > px:  # (only ever down)
            im = im.resize((px, px), Image.LANCZOS)
        im.save(dst, "JPEG", quality=quality, optimize=True, subsampling=2)


FLAT_STD = 6.0  # a tile this even (grayscale standard deviation) is one flat color
FLAT_SIDES_BAD = 8  # a spot with this many of its 16 side tiles flat is a broken render (black, one
# color, inside a wall): measured over the first 1,800 spots, 1,700 have none, the broken purple
# Darnassus ones 8-14


def flat_sides(master: Path) -> int:
    """How many of a spot's 16 side tiles (faces F, R, B, L) are nearly one flat color."""
    from PIL import ImageStat
    n = 0
    for t in sorted((master / "cube").glob("*.jpg")):
        if t.stem[0] in "FRBL":
            with Image.open(t) as im:
                if ImageStat.Stat(im.convert("L").resize((64, 64))).stddev[0] < FLAT_STD:
                    n += 1
    return n


def reported_in_game(wow: Path) -> dict[str, int]:
    """The street views players reported as broken in Street Guess (the game's saved settings,
    AzerothGPSStreetViewDB.reported = { [id] = time }), over every account in the game folder."""
    out: dict[str, int] = {}
    for sv in (wow / "WTF" / "Account").glob("*/SavedVariables/AzerothGPS_StreetView.lua"):
        text = sv.read_text(encoding="utf-8", errors="replace")
        m = re.search(r'\["reported"\]\s*=\s*\{(.*?)\n\s*\}', text, re.S)
        if m:
            for pid, t in re.findall(r'\["([^"]+)"\]\s*=\s*(\d+)', m.group(1)):
                out[pid] = max(out.get(pid, 0), int(t))
    return out


def retake(build: Path, points: dict, reported: dict[str, int] | None = None) -> dict[str, dict]:
    """The spots to take again, held back from the packs: broken renders (flat_sides, measured once
    a spot and kept in points.json) and those reported in game after their current picture was
    imported. Written to build/retake.json ({ id: { reason, ... } }) for the capture PC."""
    out: dict[str, dict] = {}
    changed = False
    for pid, p in points.items():
        master = build / "master" / pid
        if "flat_sides" not in p and (master / "cube").is_dir():
            p["flat_sides"] = flat_sides(master)
            changed = True
        if p.get("flat_sides", 0) >= FLAT_SIDES_BAD:
            out[pid] = {"reason": f"broken render: {p['flat_sides']} of 16 side tiles one flat color",
                        "cont": p["cont"], "x": p["x"], "y": p["y"], "zone": p.get("zone", "")}
    for pid, t in (reported or {}).items():
        p = points.get(pid)
        if p and t >= p.get("imported_at", 0):
            out.setdefault(pid, {"cont": p["cont"], "x": p["x"], "y": p["y"], "zone": p.get("zone", "")})
            out[pid]["reason"] = "reported in game" + (f"; {out[pid]['reason']}" if "reason" in out[pid] else "")
    if changed:
        (build / "points.json").write_text(json.dumps(points, indent=1), encoding="utf-8")
    (build / "retake.json").write_text(json.dumps(out, indent=1), encoding="utf-8")
    return out


def ship_points(points: list[dict], spacing: float | None) -> list[dict]:
    """The spots shipped at about `spacing` yards apart (packs.json ship_spacing_yd): the master keeps
    every rendered spot (100 yd), the packs take a thinned set. Greedy in a fixed order (continent,
    x, y): a spot is kept unless a kept one is within 0.75 * spacing (so neighbors along a road end up
    ~0.75-1.5 spacing apart, ~0.9 on average). None or 0: every spot."""
    if not spacing:
        return list(points)
    mind = 0.75 * spacing
    keep, grid = [], {}
    for p in sorted(points, key=lambda p: (int(p["cont"]), float(p["x"]), float(p["y"]), p["id"])):
        c, x, y = int(p["cont"]), float(p["x"]), float(p["y"])
        k = (c, int(x // mind), int(y // mind))
        near = False
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for q in grid.get((c, k[1] + dx, k[2] + dy), ()):
                    if (x - q[0]) ** 2 + (y - q[1]) ** 2 < mind * mind:
                        near = True
        if not near:
            keep.append(p)
            grid.setdefault(k, []).append((x, y))
    return keep


def build_packs(build: Path, version: str | None = None, cfg: dict | None = None,
                manual: bool = False, reported: dict[str, int] | None = None) -> list[dict]:
    """Write every SD pack addon (packs.json) into build/packs/<name>/: its toc, Index.lua and
    the tiles of its spots scaled down from the master (single views for spots not stitched
    yet). Stale folders go. Refuses a pack over the budget. Returns one report per pack:
    { name, title, points, bytes, planned }. Manual captures stay out unless `manual` (tests)."""
    cfg = cfg or CONFIG
    migrate(build)
    points_file = build / "points.json"
    points = json.loads(points_file.read_text(encoding="utf-8")) if points_file.exists() else {}
    version = version or dt.date.today().strftime("%Y.%m.%d")
    held = retake(build, points, reported)  # (broken or reported: taken again, not shipped meanwhile)
    road_diff = build / "road-diff.json"  # (sv.cmd roads: spots whose road is gone)
    retired = set(json.loads(road_diff.read_text(encoding="utf-8")).get("retired", {})) if road_diff.exists() else set()
    sd = cfg["sd"]
    root = build / "packs"
    names = {pk["name"] for pk in sd["packs"]}
    if root.exists():
        for d in root.iterdir():
            if d.is_dir() and d.name not in names:
                shutil.rmtree(d)
    reports = []
    for pk in sd["packs"]:
        # (a spot in no zone is outside the Classic game's world: Gilneas behind the Greymane Wall)
        mine = [p for p in points.values() if pack_for(cfg, p) is pk and (manual or not is_manual(p))
                and p["id"] not in held and p["id"] not in retired and (p.get("zone") or is_manual(p))]
        mine = ship_points(mine, cfg.get("ship_spacing_yd"))
        out = root / pk["name"]
        images = out / "Images"
        images.mkdir(parents=True, exist_ok=True)
        keep = {p["id"] for p in mine}
        for d in images.iterdir():
            if d.is_dir() and d.name not in keep:
                shutil.rmtree(d)
        for p in mine:
            master = build / "master" / p["id"]
            if p.get("cube") and (master / "cube").is_dir():
                if (images / p["id"]).exists():
                    for f in (images / p["id"]).glob("*.jpg"):
                        f.unlink()  # (single views from before the stitch)
                for t in (master / "cube").glob("*.jpg"):
                    px = sd["pole"] if t.stem[0] in "UD" else sd["tile"]
                    _scaled(t, images / p["id"] / "cube" / t.name, px, sd["quality"])
            elif (master / "views").is_dir():
                (images / p["id"]).mkdir(parents=True, exist_ok=True)
                for f in (master / "views").glob("*.jpg"):
                    if not (images / p["id"] / f.name).exists():
                        shutil.copy2(f, images / p["id"] / f.name)
        if pk.get("in_viewer"):  # (the viewer's own toc lists Index.lua)
            (out / f"{pk['name']}.toc").unlink(missing_ok=True)
        else:
            (out / f"{pk['name']}.toc").write_text(toc(version, f"AzerothGPS StreetView: {pk['title']}"), encoding="utf-8")
        (out / "Index.lua").write_text(index_lua(mine, version, pk["name"]), encoding="utf-8")
        size = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
        if size > cfg["budget_bytes"]:
            raise SystemExit(f"{pk['name']} is {size / 1e9:.2f} GB: over the {cfg['budget_bytes'] / 1e9:.1f} GB "
                             "budget for one CurseForge file. Lower the SD tile size or split the pack first.")
        reports.append({"name": pk["name"], "title": pk["title"], "points": len(mine), "bytes": size,
                        "planned": pk["planned"], "held": len(held)})
    return reports


def budget(reports: list[dict], cfg: dict | None = None) -> str:
    """Each pack now and projected to all its planned spots, against the CurseForge budget."""
    cfg = cfg or CONFIG
    lim = cfg["budget_bytes"]
    ship = cfg.get("ship_spacing_yd") or cfg["spacing_yd"]
    lines = [f"packs (limit {lim / 1e9:.1f} GB each, rendered every {cfg['spacing_yd']} yd, shipped every ~{ship} yd):"]
    for r in reports:
        per = r["bytes"] / r["points"] if r["points"] else 0
        full = per * r["planned"]
        line = f"  {r['title']}: {r['points']} spots, {r['bytes'] / 1e6:.1f} MB"
        if r["points"]:
            line += f" ({per / 1e3:.0f} KB a spot; all {r['planned']} planned: {full / 1e9:.2f} GB)"
            if full > lim:
                line += "  WOULD BE OVER THE LIMIT"
        lines.append(line)
    held = reports[0].get("held", 0) if reports else 0
    if held:
        lines.append(f"  held back to take again: {held} (build/retake.json: broken renders and pictures reported in game)")
    return "\n".join(lines)


def build_pack(build: Path, version: str | None = None, manual: bool = False) -> tuple[int, int]:
    """(Older callers) build every pack; returns (spots, bytes) over all of them."""
    reports = build_packs(build, version, manual=manual)
    return sum(r["points"] for r in reports), sum(r["bytes"] for r in reports)
