-- Street views from the installed data packs, and the maths the viewer and the map figure
-- share. No frames here: this file is tested under lupa (tests/test_lua.py).
--
-- A data pack (AzerothGPS_StreetView_Data, generated by tools/sv.py) adds itself to
-- AzerothGPS_StreetViewPacks:
--   { name, version, ext = "jpg", root = "Interface\\AddOns\\<pack>\\Images\\",
--     points = { { id, cont, x, y, z, facing, zone, poses = { ["y000_p+00"] = true, ... } } } }
-- World coordinates are AzerothGPS's: yards, x north, y west. `facing` is the heading of the
-- point's first view (yaw index 0) in radians, counter-clockwise from north.
local _, ns = ...

local D = {}
ns.Data = D

-- The views of a point: rings of 8 (45 degrees apart) looking down, level and up, plus one
-- straight down and one straight up. Pitch indexes run from the lowest.
D.PITCHES = { -90, -45, 0, 45, 90 }
D.LEVEL = 3 -- index of the level ring
D.YAWS = 8
D.STEP = math.pi / 4
-- Which way FlipCameraYaw turned the capture's views: 1 = counter-clockwise (to the left)
-- for positive angles. /sv flipyaw switches it if the views turn the wrong way.
D.yawSign = 1

D.byCont, D.byId, D.count = {}, {}, 0

-- Read the installed packs. Returns the number of views.
function D.Load(packs)
  packs = packs or _G.AzerothGPS_StreetViewPacks
  D.byCont, D.byId, D.count = {}, {}, 0
  if type(packs) ~= "table" then return 0 end
  for _, pack in ipairs(packs) do
    if type(pack) == "table" and type(pack.points) == "table" and type(pack.root) == "string" then
      for _, p in ipairs(pack.points) do
        if type(p) == "table" and p.id and tonumber(p.x) and tonumber(p.y) and p.cont then
          p.pack = pack
          if not D.byId[p.id] then D.count = D.count + 1 end
          D.byId[p.id] = p -- (a later pack's copy wins)
        end
      end
    end
  end
  for _, p in pairs(D.byId) do
    D.byCont[p.cont] = D.byCont[p.cont] or {}
    table.insert(D.byCont[p.cont], p)
  end
  return D.count
end

function D.PointsOn(cont) return D.byCont[cont] or {} end

-- The view nearest to (x, y) on `cont`, and its distance; nil when none is within maxDist.
function D.Nearest(cont, x, y, maxDist)
  local best, bestD2
  for _, p in ipairs(D.byCont[cont] or {}) do
    local d2 = (p.x - x) ^ 2 + (p.y - y) ^ 2
    if not bestD2 or d2 < bestD2 then best, bestD2 = p, d2 end
  end
  if not best or (maxDist and bestD2 > maxDist * maxDist) then return nil end
  return best, math.sqrt(bestD2)
end

-- Angle a - b wrapped to [-pi, pi).
function D.AngleDiff(a, b)
  return (a - b + math.pi) % (2 * math.pi) - math.pi
end

-- Heading (radians, counter-clockwise from north) from world (x1, y1) to (x2, y2).
function D.Bearing(x1, y1, x2, y2)
  local atan2 = math.atan2 or math.atan
  return atan2(y2 - y1, x2 - x1)
end

-- Heading of point p's view `yaw` (0..7).
function D.Heading(p, yaw)
  return (p.facing or 0) + D.yawSign * yaw * D.STEP
end

-- The view (0..7) of point p looking closest to `heading`.
function D.YawFor(p, heading)
  local rel = D.AngleDiff(heading, p.facing or 0) * D.yawSign
  return math.floor(rel / D.STEP + 0.5) % D.YAWS
end

-- One view to the right (dir = 1) or left (dir = -1) of view `yaw`.
function D.Turn(p, yaw, dir)
  return D.YawFor(p, D.Heading(p, yaw) - dir * D.STEP)
end

local COMPASS = { "N", "NW", "W", "SW", "S", "SE", "E", "NE" } -- counter-clockwise from north
function D.Compass(heading)
  return COMPASS[math.floor(heading / D.STEP + 0.5) % 8 + 1]
end

-- The nearest other view ahead of point p, looking along `heading`: within maxDist yards and
-- maxAngle of straight ahead (defaults 150 yd, 50 degrees), preferring near and straight.
function D.Ahead(p, heading, maxDist, maxAngle)
  maxDist, maxAngle = maxDist or 150, maxAngle or math.rad(50)
  local best, bestScore
  for _, q in ipairs(D.byCont[p.cont] or {}) do
    if q ~= p then
      local d = math.sqrt((q.x - p.x) ^ 2 + (q.y - p.y) ^ 2)
      if d > 0.5 and d <= maxDist then
        local off = math.abs(D.AngleDiff(D.Bearing(p.x, p.y, q.x, q.y), heading))
        if off <= maxAngle then
          local score = d * (1 + off)
          if not bestScore or score < bestScore then best, bestScore = q, score end
        end
      end
    end
  end
  return best
end

-- Image file name of a view (straight up and down have one view each: yaw 0).
function D.PoseName(yaw, pitch)
  if pitch == 90 or pitch == -90 then yaw = 0 end
  return string.format("y%03d_p%s%02d", yaw * 45, pitch < 0 and "-" or "+", math.abs(pitch))
end

function D.HasPose(p, yaw, pitch)
  return p.poses == nil or p.poses[D.PoseName(yaw, pitch)] == true
end

function D.ImagePath(p, yaw, pitch)
  local pack = p.pack or {}
  return (pack.root or "") .. p.id .. "\\" .. D.PoseName(yaw, pitch) .. "." .. (pack.ext or "jpg")
end
