-- Street views from the installed data packs, and the maths the viewer and the map figure
-- share. No frames here: this file is tested under lupa (tests/test_lua.py).
--
-- A data pack (AzerothGPS_StreetView_Data, generated by tools/sv.py) adds itself to
-- AzerothGPS_StreetViewPacks:
--   { name, version, ext = "jpg", root = "Interface\\AddOns\\<pack>\\Images\\",
--     points = { { id, cont, x, y, z, facing, zone, poses = { ["y000_p+00"] = true, ... } } } }
-- World coordinates are AzerothGPS's: yards, x north, y west. `facing` is the heading of the
-- point's first view (yaw index 0) in radians, counter-clockwise from north.
local _, ns = ...

local D = {}
ns.Data = D

-- The views of a point: rings of 8 (45 degrees apart) looking down, level and up, plus one
-- straight down and one straight up. Pitch indexes run from the lowest.
D.PITCHES = { -90, -45, 0, 45, 90 }
D.LEVEL = 3 -- index of the level ring
D.YAWS = 8
D.STEP = math.pi / 4
-- Which way FlipCameraYaw turned the capture's views: 1 = counter-clockwise (to the left)
-- for positive angles. /sv flipyaw switches it if the views turn the wrong way.
D.yawSign = 1

D.byCont, D.byId, D.count, D.packs = {}, {}, 0, {}

-- Read the installed packs. Returns the number of views.
function D.Load(packs)
  packs = packs or _G.AzerothGPS_StreetViewPacks
  D.byCont, D.byId, D.count, D.packs = {}, {}, 0, {}
  if type(packs) ~= "table" then return 0 end
  for _, pack in ipairs(packs) do
    if type(pack) == "table" and type(pack.points) == "table" and type(pack.root) == "string" then
      D.packs[#D.packs + 1] = pack -- (the installed packs: { name, version, ... })
      for _, p in ipairs(pack.points) do
        if type(p) == "table" and p.id and tonumber(p.x) and tonumber(p.y) and p.cont then
          p.pack = pack
          if not D.byId[p.id] then D.count = D.count + 1 end
          D.byId[p.id] = p -- (a later pack's copy wins)
        end
      end
    end
  end
  for _, p in pairs(D.byId) do
    D.byCont[p.cont] = D.byCont[p.cont] or {}
    table.insert(D.byCont[p.cont], p)
  end
  return D.count
end

function D.PointsOn(cont) return D.byCont[cont] or {} end

-- The view nearest to (x, y) on `cont`, and its distance; nil when none is within maxDist.
function D.Nearest(cont, x, y, maxDist)
  local best, bestD2
  for _, p in ipairs(D.byCont[cont] or {}) do
    local d2 = (p.x - x) ^ 2 + (p.y - y) ^ 2
    if not bestD2 or d2 < bestD2 then best, bestD2 = p, d2 end
  end
  if not best or (maxDist and bestD2 > maxDist * maxDist) then return nil end
  return best, math.sqrt(bestD2)
end

-- Angle a - b wrapped to [-pi, pi).
function D.AngleDiff(a, b)
  return (a - b + math.pi) % (2 * math.pi) - math.pi
end

-- Heading (radians, counter-clockwise from north) from world (x1, y1) to (x2, y2).
function D.Bearing(x1, y1, x2, y2)
  local atan2 = math.atan2 or math.atan
  return atan2(y2 - y1, x2 - x1)
end

-- Heading of point p's view `yaw` (0..7).
function D.Heading(p, yaw)
  return (p.facing or 0) + D.yawSign * yaw * D.STEP
end

-- The view (0..7) of point p looking closest to `heading`.
function D.YawFor(p, heading)
  local rel = D.AngleDiff(heading, p.facing or 0) * D.yawSign
  return math.floor(rel / D.STEP + 0.5) % D.YAWS
end

-- One view to the right (dir = 1) or left (dir = -1) of view `yaw`.
function D.Turn(p, yaw, dir)
  return D.YawFor(p, D.Heading(p, yaw) - dir * D.STEP)
end

local COMPASS = { "N", "NW", "W", "SW", "S", "SE", "E", "NE" } -- counter-clockwise from north
function D.Compass(heading)
  return COMPASS[math.floor(heading / D.STEP + 0.5) % 8 + 1]
end

-- How far the arrows and "Go ahead" reach: a little past one step (spots are about 100 yd
-- apart along the roads), so a click lands on the next spot, never one further on.
D.NEXT_RANGE = 130

-- The nearest other view ahead of point p, looking along `heading`: within maxDist yards and
-- maxAngle of straight ahead (defaults D.NEXT_RANGE, 50 degrees), the nearest first: a spot
-- a little off to the side beats a straighter one further on (a road bending on a diagonal).
function D.Ahead(p, heading, maxDist, maxAngle)
  maxDist, maxAngle = maxDist or D.NEXT_RANGE, maxAngle or math.rad(50)
  local best, bestScore
  for _, q in ipairs(D.byCont[p.cont] or {}) do
    if q ~= p then
      local d = math.sqrt((q.x - p.x) ^ 2 + (q.y - p.y) ^ 2)
      if d > 0.5 and d <= maxDist then
        local off = math.abs(D.AngleDiff(D.Bearing(p.x, p.y, q.x, q.y), heading))
        if off <= maxAngle then
          local score = d * (1 + 0.5 * off)
          if not bestScore or score < bestScore then best, bestScore = q, score end
        end
      end
    end
  end
  return best
end

-- Image file name of a view (straight up and down have one view each: yaw 0).
function D.PoseName(yaw, pitch)
  if pitch == 90 or pitch == -90 then yaw = 0 end
  return string.format("y%03d_p%s%02d", yaw * 45, pitch < 0 and "-" or "+", math.abs(pitch))
end

function D.HasPose(p, yaw, pitch)
  return p.poses == nil or p.poses[D.PoseName(yaw, pitch)] == true
end

function D.ImagePath(p, yaw, pitch)
  local pack = p.pack or {}
  return (pack.root or "") .. p.id .. "\\" .. D.PoseName(yaw, pitch) .. "." .. (pack.ext or "jpg")
end

-- Panoramas (a point with `pano = { cols, rows }`): one 360-degree picture in tiles,
-- Images/<id>/pano/t<col><row>.jpg. Its middle column looks along `facing`; columns to the
-- right turn right. A direction in it is `lon` (degrees, clockwise from facing, -180..180)
-- and `lat` (degrees up).
function D.HasPano(p)
  return type(p.pano) == "table" and (p.pano.cols or 0) > 0 and (p.pano.rows or 0) > 0
end

function D.PanoPath(p, col, row)
  local pack = p.pack or {}
  return (pack.root or "") .. p.id .. "\\pano\\t" .. col .. row .. "." .. (pack.ext or "jpg")
end

function D.PanoHeading(p, lon) return (p.facing or 0) - math.rad(lon) end
function D.PanoLon(p, heading) return math.deg(D.AngleDiff(p.facing or 0, heading)) end

-- The tiles a view of the panorama needs: looking at (lon, lat) with `fov` degrees across a
-- window w x h UI units. Returns the list { col, row, x, y, size } (x, y: the tile's top-left
-- from the window's top-left, y down; size: its edge in UI units) and lat kept inside the
-- picture. The panorama is laid flat (a pan, not a perspective view).
function D.PanoTiles(p, lon, lat, fov, w, h)
  local cols, rows = p.pano.cols, p.pano.rows
  local tw, th = 360 / cols, 180 / rows -- degrees per tile (square tiles: tw == th)
  local ppd = w / fov
  local vspan = h / ppd
  local limit = math.max(0, 90 - vspan / 2)
  lat = math.max(-limit, math.min(limit, lat))
  local left, top = lon - fov / 2, lat + vspan / 2
  local out = {}
  for c = 0, cols - 1 do
    local dx = ((-180 + c * tw) - left) % 360
    if dx > 360 - tw then dx = dx - 360 end -- (a tile straddling the window's left edge)
    if dx < fov and dx + tw > 0 then
      for r = 0, rows - 1 do
        local dy = top - (90 - r * th)
        if dy < vspan and dy + th > 0 then
          out[#out + 1] = { col = c, row = r, x = dx * ppd, y = dy * ppd, size = tw * ppd }
        end
      end
    end
  end
  return out, lat
end

-- The ways you can go from a spot, as headings (radians, counter-clockwise from north): along
-- every road within `radius` yards of it (both ways, except past a road's end) and toward
-- the nearest other street view each way within `near` yards (D.NEXT_RANGE). Directions within
-- `merge` of one already found count once, so a spot further on behind a nearer one adds no
-- arrow. `roads` is AzerothGPS's road network of the spot's continent ({ e = { { a, b, len,
-- source, x, y, x, y, ... } } }), nil for none.
function D.Directions(p, roads, radius, near, merge)
  radius, near, merge = radius or 12, near or D.NEXT_RANGE, merge or math.rad(25)
  local dirs = {}
  local function add(h)
    h = h % (2 * math.pi)
    for _, d in ipairs(dirs) do
      if math.abs(D.AngleDiff(h, d)) < merge then return end
    end
    dirs[#dirs + 1] = h
  end
  local x, y = p.x, p.y
  if type(roads) == "table" and type(roads.e) == "table" then
    local r2 = radius * radius
    for _, e in ipairs(roads.e) do
      for i = 5, #e - 3, 2 do
        local ax, ay, bx, by = e[i], e[i + 1], e[i + 2], e[i + 3]
        if not ((ax < x - radius and bx < x - radius) or (ax > x + radius and bx > x + radius)
            or (ay < y - radius and by < y - radius) or (ay > y + radius and by > y + radius)) then
          local vx, vy = bx - ax, by - ay
          local len2 = vx * vx + vy * vy
          if len2 > 0 then
            local t = math.max(0, math.min(1, ((x - ax) * vx + (y - ay) * vy) / len2))
            local dx, dy = ax + vx * t - x, ay + vy * t - y
            if dx * dx + dy * dy <= r2 then
              local h = D.Bearing(ax, ay, bx, by)
              if t < 1 then add(h) end -- (road goes on ahead)
              if t > 0 then add(h + math.pi) end -- (and back)
            end
          end
        end
      end
    end
  end
  local close = {}
  for _, q in ipairs(D.byCont[p.cont] or {}) do
    local d2 = (q.x - x) ^ 2 + (q.y - y) ^ 2
    if q ~= p and d2 <= near * near then close[#close + 1] = { q = q, d2 = d2 } end
  end
  table.sort(close, function(a, b) return a.d2 < b.d2 end) -- (nearest first: it owns its direction)
  for _, c in ipairs(close) do add(D.Bearing(x, y, c.q.x, c.q.y)) end
  return dirs
end

-- Cubes (a point with `cube = { pad }`): the spot seen as six square faces, each in four
-- tiles, Images/<id>/cube/<face><col><row>.jpg, drawn in true perspective (turning feels like
-- turning your head). The faces as (normal, right, up) in the spot's frame: x right, y up,
-- z forward along `facing`. Keep in step with tools/svtools/stitch.py FACES.
D.FACES = {
  F = { { 0, 0, 1 }, { 1, 0, 0 }, { 0, 1, 0 } },
  R = { { 1, 0, 0 }, { 0, 0, -1 }, { 0, 1, 0 } },
  B = { { 0, 0, -1 }, { -1, 0, 0 }, { 0, 1, 0 } },
  L = { { -1, 0, 0 }, { 0, 0, 1 }, { 0, 1, 0 } },
  U = { { 0, 1, 0 }, { 1, 0, 0 }, { 0, 0, -1 } },
  D = { { 0, -1, 0 }, { 1, 0, 0 }, { 0, 0, 1 } },
}
D.FACE_NAMES = { "F", "R", "B", "L", "U", "D" }

function D.HasCube(p)
  return type(p.cube) == "table"
end

function D.CubePath(p, face, col, row)
  local pack = p.pack or {}
  return (pack.root or "") .. p.id .. "\\cube\\" .. face .. col .. row .. "." .. (pack.ext or "jpg")
end

local function dot(a, x, y, z) return a[1] * x + a[2] * y + a[3] * z end

-- The face a direction points at most (largest component along a face's normal).
function D.CubeFace(x, y, z)
  local best, bestDot
  for _, name in ipairs(D.FACE_NAMES) do
    local d = dot(D.FACES[name][1], x, y, z)
    if not bestDot or d > bestDot then best, bestDot = name, d end
  end
  return best
end

-- A direction's coordinates on a face (a right, b up; -1..1 on the face), nil behind it.
function D.CubeCoords(face, x, y, z)
  local f = D.FACES[face]
  local n = dot(f[1], x, y, z)
  if n <= 1e-6 then return nil end
  return dot(f[2], x, y, z) / n, dot(f[3], x, y, z) / n
end

-- Right, up and forward of a view looking lon degrees clockwise from facing, lat degrees up.
function D.ViewAxes(lon, lat)
  local yaw, pitch = -math.rad(lon), math.rad(lat)
  local L = -yaw
  local cp, sp, cl, sl = math.cos(pitch), math.sin(pitch), math.cos(L), math.sin(L)
  return { cl, 0, -sl }, { -sl * sp, cp, -cl * sp }, { sl * cp, sp, cl * cp }
end

-- The view as a grid of cols x rows cells over a window w x h (UI units), looking at
-- (lon, lat) with fov degrees across: for each cell its rectangle (x, y from the window's
-- top-left, y down; cw, ch), its tile (face, col, row) and the texture coordinates of its
-- corners in that tile's image (ulx, uly, llx, lly, urx, ury, lrx, lry: SetTexCoord's order).
-- Small cells cut in perspective: straight lines stay straight to the eye. A cell reaching
-- past its tile's image (near a cube edge in a wide view) is split in four, up to twice.
function D.CubeCells(p, lon, lat, fov, w, h, cols, rows)
  local pad = (p.cube and p.cube.pad) or 0.08
  local span = 1 + 2 * pad
  local r, u, fw = D.ViewAxes(lon, lat)
  local f = (w / 2) / math.tan(math.rad(fov) / 2)
  local function dir(x, y) -- the direction screen point (x, y) looks along
    local X, Y = x - w / 2, h / 2 - y
    return X * r[1] + Y * u[1] + f * fw[1], X * r[2] + Y * u[2] + f * fw[2], X * r[3] + Y * u[3] + f * fw[3]
  end
  local out = {}
  local function cell(x0, y0, x1, y1, depth)
    local face = D.CubeFace(dir((x0 + x1) / 2, (y0 + y1) / 2))
    local ca, cb = D.CubeCoords(face, dir((x0 + x1) / 2, (y0 + y1) / 2))
    local col, row = ca < 0 and 0 or 1, cb >= 0 and 0 or 1
    local a0 = (col == 0 and -1 or 0) - pad
    local b1 = (row == 0 and 1 or 0) + pad
    local uv, fits = {}, true
    for _, c in ipairs({ { x0, y0 }, { x0, y1 }, { x1, y0 }, { x1, y1 } }) do -- (UL, LL, UR, LR)
      local a, b = D.CubeCoords(face, dir(c[1], c[2]))
      if not a then fits = false break end
      local tu, tv = (a - a0) / span, (b1 - b) / span
      if tu < -0.001 or tu > 1.001 or tv < -0.001 or tv > 1.001 then fits = false end
      local n = #uv
      uv[n + 1] = tu
      uv[n + 2] = tv
    end
    if not fits and depth < 2 then
      local mx, my = (x0 + x1) / 2, (y0 + y1) / 2
      cell(x0, y0, mx, my, depth + 1)
      cell(mx, y0, x1, my, depth + 1)
      cell(x0, my, mx, y1, depth + 1)
      cell(mx, my, x1, y1, depth + 1)
    elseif #uv == 8 then
      out[#out + 1] = { x = x0, y = y0, cw = x1 - x0, ch = y1 - y0, face = face, col = col, row = row, uv = uv }
    end
  end
  for j = 0, rows - 1 do
    for i = 0, cols - 1 do
      cell(i * w / cols, j * h / rows, (i + 1) * w / cols, (j + 1) * h / rows, 0)
    end
  end
  return out
end

-- Where a ground direction appears in such a view: heading `dir` (radians), `below` degrees
-- under the horizon; returns x, y from the window's top-left, or nil when behind the viewer.
function D.CubeProject(p, lon, lat, fov, w, h, dir, below)
  local r, u, fw = D.ViewAxes(lon, lat)
  local f = (w / 2) / math.tan(math.rad(fov) / 2)
  local L, el = math.rad(D.PanoLon(p, dir)), -math.rad(below)
  local x, y, z = math.sin(L) * math.cos(el), math.sin(el), math.cos(L) * math.cos(el)
  local zc = x * fw[1] + y * fw[2] + z * fw[3]
  if zc <= 1e-3 then return nil end
  local xc = x * r[1] + y * r[2] + z * r[3]
  local yc = x * u[1] + y * u[2] + z * u[3]
  return w / 2 + f * xc / zc, h / 2 - f * yc / zc
end
