-- The street views this addon ships: generated by tools/sv.py (`sv.cmd build`) into
-- build/packs/AzerothGPS_StreetView/Index.lua with the pictures in Images/, and laid over this
-- file by `sv.cmd install` and `sv.cmd release`. Empty here: the pictures never go into git.
AzerothGPS_StreetViewPacks = AzerothGPS_StreetViewPacks or {}
